##################################################
################ General Settings ################
##################################################

GeneralSettings:
  botToken: "NTc2NzQ3NDM1NjUzNTk1MTM2.XNa_6A.NQVX3VkyrfoNtCcilzmS0Spjfig"

  noPermissionERROR: "ä½ ä¸¦æ²’æœ‰æ¬Šé™åŸ·è¡Œæ­¤å‹•ä½œ, è«‹ä¿æŒè‰¯æ°‘ä»¥æè¡›è‡ªèº«æ¬Šç›Š"
  helpBlockFooter: "åŸä¹‹åº | ORDERLY SERVER"

  folder:
    channelLogFolder: "channelLog"
    configFolder: "configFolder"

  # Can pass permission limit
  botOwnerID:
    - "286467027705790464" # WavJaby#3673
    - "810822763601461318" # XinShou#0404
    - "270062130470846465" # XinShou#8787
    - "308721713066147840" # é˜¿æ­£#6176
    - "860182127798124594" # XinShou#1699

  # watching / listening / playing / competing / streaming
  activityMessage:
    - "listening;åŸä¹‹åº | ORDERLY SERVER"
    - "listening;ç„¡æéŸ³è³ªéŸ³æ¨‚"
    - "listening;ç°¡ç´„æŠ•ç¥¨ç³»çµ±"
    - "listening;æœ‰ä»»ä½•å•é¡Œæ­¡è¿é€šçŸ¥ XinShou#0404"
    - "competing;è²“è²“â¤ç‹—ç‹—"
    - "competing;éº»éº»â¤æ–°æ‰‹"

  # Youtube API KEY (https:// console.cloud.google.com/apis/)
  apiKey: "AIzaSyA6KoqXbs5ZI2Zqlo-BcUPULQDBe8fVWPw"

  # Will send command used message to console
  debugMode: true


##################################################
################## ID Settings ###################
##################################################

IDSettings:
  guildID: "858672865355890708"
  logChannelID: "858672865816346634"
  authChannelID: "860469251176792065"
  consoleChannelID: "861936727329472512"
  informationChannelID: "858672865444626439"

  botRoleID: "858972360609366037"
  logRoleID: "858672865355890715"
  memberRoleID: "858672865385119757"
  boostedRoleID: "858706338199896084"
  internalRoleID: "865566302773051454"

  adminPermissionID: "858672865444626433"

  # When member join the server will get role(s).
  joinRoleID:
    - "858707058530451476"
    - "858703314606751764"
    - "858701368457953360"
    - "858672865385119755"

  # When member pass the auth can get role(s).
  confirmRoleID:
    - "858672865385119757"
    - "858704345448841226"


##################################################
################ Rooms Settings ##################
##################################################

RoomSettings:
  defaultRoomName: "ã€ŠğŸ”Šã€‹%name% æˆ¿é–“"
  defaultRoomChatName: "ã€ŠğŸ“„ã€‹%name% æ–‡å­—é »é“"
  defaultRoomBitrate: 128000

  roomCategoryID:
    - "862530693766316052"
    - "865142236977823754"
    - "865145008070852638"
    - "865145523844284426"
    - "865145543758970881"
    - "865145566069522462"
    - "865145587028721674"
    - "865145607928938516"
    - "865145631622692874"
    - "865145649612062730"


##################################################
############## Services Settings #################
##################################################

ServiceSettings:
  newServiceName: "ã€Šâ—ã€‹%name% å®¢æœ"
  defaultServiceMessage: "%reporter% æ‚¨å¥½, è«‹èªªæ˜æ‚¨çš„å•é¡Œ, å·¥ç¨‹çµ„å°‡æœƒåœ¨ä¸ä¹…å¾Œè¯çµ¡æ‚¨"

  serviceCategoryID:
    - "864673016653807627"

  serviceTagRoleID:
    - "858672865409630245"


##################################################
################### MutiBot ######################
##################################################

MultiBot:
  tokens:
    - "NjA4MDgwNjE4ODk4ODQ5ODI1.XUi9NQ.K8XYERpv6Lsn5KSv3ORgBXOeUGc" # çŠ¬
#    - "ODY3MzEyMzI3MDQ0NjI4NDgw.YPfRjA.pvtrfv3OzDqiLNGz9c_4unX-310" # ç‹
#    - "Njc5MzMwNzU4MTkxNDgwODY0.XkvyEg.La_10QDAWVoGL0DsuofwUQCpke4" # èˆ
#    - "NjM1NDc0MDE3MDM3NDUxMjc1.XaxlTA.3HDGP6fzHwaJTwxDqdRdgBq7qis" # è±¬
#    - "ODY3MzExMjU5NTkzOTk4MzQ3.YPfQjg.X7kJLIEXrjOXLpCm8y75nmjARiQ" # è²“

  randomBot: true
